// build.mjs — scans the /photos folder and regenerates photos.js
// Run it any time you add or remove photos:   node build.mjs
//
// Captions: edit captions.json (a simple { "filename.jpg": "Your caption" } map).
// This script merges it in, so rebuilding never erases your captions.

import { readdirSync, writeFileSync, existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

const PHOTO_DIR = 'photos';
const EXT = new Set(['.jpg', '.jpeg', '.png', '.webp', '.avif', '.gif']);

// natural sort so "img2" comes before "img10"
const collator = new Intl.Collator(undefined, { numeric: true, sensitivity: 'base' });

let captions = {};
if (existsSync('captions.json')) {
  try { captions = JSON.parse(readFileSync('captions.json', 'utf8')); }
  catch { console.warn('⚠  captions.json is not valid JSON — ignoring it.'); }
}

if (!existsSync(PHOTO_DIR)) {
  console.error(`✗ No "${PHOTO_DIR}" folder found. Create it and drop your images in.`);
  process.exit(1);
}

const files = readdirSync(PHOTO_DIR)
  .filter(f => EXT.has(f.slice(f.lastIndexOf('.')).toLowerCase()))
  .sort(collator.compare);

const photos = files.map(f => {
  const caption = captions[f] ?? '';
  return { src: `${PHOTO_DIR}/${encodeURIComponent(f)}`, title: caption };
});

const out =
`// AUTO-GENERATED by build.mjs — do not edit by hand.
// ${photos.length} photo(s). To add captions, edit captions.json then rerun: node build.mjs
window.PHOTOS = ${JSON.stringify(photos, null, 2)};
`;

writeFileSync('photos.js', out);

// keep a captions.json template in sync so new files show up ready to caption
const merged = {};
for (const f of files) merged[f] = captions[f] ?? '';
writeFileSync('captions.json', JSON.stringify(merged, null, 2));

console.log(`✓ Found ${photos.length} photo(s). Wrote photos.js`);
if (photos.length === 0) console.log('  (folder is empty — drop images into /photos and rerun)');
else console.log('  Open index.html in your browser to view the gallery.');
