// build.mjs — scans the /photos folder and regenerates albums.js
// Run it any time you add or remove photos:   node build.mjs
//
// HOW ALBUMS WORK
//   Each sub-folder of /photos is an album:
//       photos/performance/IMG_1.jpg   -> album "performance"
//       photos/iceland/sunrise.jpg     -> album "iceland"
//   Photos dropped directly in /photos (no sub-folder) go into a "Moments" album.
//
//   Album titles, descriptions, covers and order live in albums.json — e.g.
//       {
//         "performance": { "title": "Berwin Art 2026 Dance", "desc": "…", "cover": "IMG_1.jpg", "order": 1 }
//       }
//   This script merges that in (and keeps a template in sync), so rebuilding
//   never erases your metadata.  Per-photo captions live in captions.json,
//   keyed by the photo's path relative to /photos (e.g. "iceland/sunrise.jpg").

import { readdirSync, writeFileSync, existsSync, readFileSync } from 'node:fs';
import { join, relative, sep } from 'node:path';

const PHOTO_DIR = 'photos';
const EXT = new Set(['.jpg', '.jpeg', '.png', '.webp', '.avif', '.gif']);
const ROOT_ALBUM = '_moments';                 // id used for photos with no sub-folder
const collator = new Intl.Collator(undefined, { numeric: true, sensitivity: 'base' });

function readJson(path){
  if(!existsSync(path)) return {};
  try { return JSON.parse(readFileSync(path, 'utf8')); }
  catch { console.warn(`⚠  ${path} is not valid JSON — ignoring it.`); return {}; }
}

// turn "iceland-2025" / "iceland_2025" into "Iceland 2025"
function prettify(id){
  if(id === ROOT_ALBUM) return 'Moments';
  return id.replace(/[-_]+/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
}

// recursively collect image files under a directory
function walk(dir){
  let out = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) out = out.concat(walk(full));
    else if (EXT.has(entry.name.slice(entry.name.lastIndexOf('.')).toLowerCase())) out.push(full);
  }
  return out;
}

if (!existsSync(PHOTO_DIR)) {
  console.error(`✗ No "${PHOTO_DIR}" folder found. Create it and drop your albums in.`);
  process.exit(1);
}

const captions = readJson('captions.json');
const meta     = readJson('albums.json');

// relative paths under photos/, forward slashes, naturally sorted
const files = walk(PHOTO_DIR)
  .map(f => relative(PHOTO_DIR, f).split(sep).join('/'))
  .sort(collator.compare);

const enc = p => p.split('/').map(encodeURIComponent).join('/');

// group files by their first path segment (the album id)
const groups = new Map();   // id -> [{ rel, src, title }]
for (const rel of files) {
  const slash = rel.indexOf('/');
  const id = slash === -1 ? ROOT_ALBUM : rel.slice(0, slash);
  if (!groups.has(id)) groups.set(id, []);
  groups.get(id).push({ rel, src: `${PHOTO_DIR}/${enc(rel)}`, title: captions[rel] ?? '' });
}

// build album objects, applying metadata
const albums = [...groups.entries()].map(([id, photos]) => {
  const m = meta[id] || {};
  let cover = null;
  if (m.cover) {
    // cover may be given as a bare filename or a path relative to photos/
    const candidate = m.cover.includes('/') ? m.cover : `${id === ROOT_ALBUM ? '' : id + '/'}${m.cover}`;
    const hit = photos.find(p => p.rel === candidate);
    if (hit) cover = hit.src;
  }
  if (!cover) cover = photos[0].src;
  return {
    id,
    title: m.title || prettify(id),
    desc:  m.desc  || '',
    order: typeof m.order === 'number' ? m.order : 999,
    cover,
    photos: photos.map(({ src, title }) => ({ src, title })),
  };
});

// order: explicit "order" first, then alphabetical by title
albums.sort((a, b) => a.order - b.order || collator.compare(a.title, b.title));

const out =
`// AUTO-GENERATED by build.mjs — do not edit by hand.
// ${albums.length} album(s), ${files.length} photo(s).
// Edit albums.json (titles/desc/cover/order) and captions.json, then rerun: node build.mjs
window.ALBUMS = ${JSON.stringify(albums.map(({ order, ...a }) => a), null, 2)};
`;
writeFileSync('albums.js', out);

// keep templates in sync so new albums/photos show up ready to label
const captionsTemplate = {};
for (const f of files) captionsTemplate[f] = captions[f] ?? '';
writeFileSync('captions.json', JSON.stringify(captionsTemplate, null, 2));

// preserve any hand-written entries (even for albums not yet on disk),
// and make sure every album with photos has a labelled entry
const metaTemplate = { ...meta };
for (const { id } of albums) {
  const m = meta[id] || {};
  metaTemplate[id] = {
    title: m.title || prettify(id),
    desc:  m.desc  || '',
    cover: m.cover || '',
    order: typeof m.order === 'number' ? m.order : 999,
  };
}
writeFileSync('albums.json', JSON.stringify(metaTemplate, null, 2));

console.log(`✓ ${albums.length} album(s), ${files.length} photo(s). Wrote albums.js`);
for (const a of albums) console.log(`   • ${a.title} — ${a.photos.length} photo(s)`);
if (files.length === 0) console.log('  (no photos yet — make a folder like photos/iceland/ and drop images in)');
